package org.uppaal.cli.enumerations;

/**
* enumeration of all possible return codes
*/

public enum ResultCode {
OK, 
MODE_CHANGED, 
EXIT, 
IO_ERROR, 
ENGINE_ERROR, 
COMPILATION_ERROR, 
EVALUATION_ERROR,
SELECT_TEMPLATES,
ADD_TEMPLATE,
ADD_TEMPLATES,
REMOVE_TEMPLATE,
CLEAR_TEMPLATES,
RENAME_TEMPLATE,
SELECT_TRANSITION,
SELECT_STATE,
SELECT_QUERIES,
SELECT_DATA
}
